version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - tobiasstamann
  assignees:
  - tobiasstamann
  ignore:
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
  - dependency-name: org.codehaus.mojo:animal-sniffer-maven-plugin
    versions:
    - "1.19"
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: org.testng:testng
    versions:
    - 7.3.0
