name: default

on:
  push:
    branches:
      - '*'
      - '**/*'
      - '!master'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest,macos-latest,windows-latest ]
        java: [ 8.0.x, 9.0.x, 10.0.x, 11.0.x, 12.0.x, 13.0.x, 14.0.x, 15.0.x, 16.0.x, 17.0.x, 18.0.x, 19.0.x, 20.0.x, 21.0.x, 22.0.x, 23.0.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Prepare mvnw
        run: chmod +x ./mvnw

      - name: Build
        run: ./mvnw clean package

