name: jacoco

on:
  push:
    branches:
      - '*'
      - '**/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 9
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 9

      - name: Cache .m2
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven
            
      - name: Prepare mvnw
        run: chmod +x ./mvnw

      - name: Build
        run: ./mvnw verify jacoco:report-aggregate -B -q

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: target/site/jacoco-aggregate/jacoco.xml
